-- =============================================================================
-- UPSERT for gold.installations_meteo
-- Source: Gold installations_meteo
-- Strategy: Insert new rows, update existing if data changed
-- =============================================================================

INSERT INTO gold.installations_meteo (
    id_peps,
    nom_installation,
    type_energie,
    code_filiere,
    filiere,
    technologie,
    puissance_max_installee,
    commune,
    departement,
    region,
    code_iris,
    centroid_lat,
    centroid_lon,
    date_mise_en_service,
    station_meteo_id,
    station_meteo_nom,
    station_meteo_lat,
    station_meteo_lon,
    distance_station_km,
    updated_at
)
VALUES (
    %(id_peps)s,
    %(nom_installation)s,
    %(type_energie)s,
    %(code_filiere)s,
    %(filiere)s,
    %(technologie)s,
    %(puissance_max_installee)s,
    %(commune)s,
    %(departement)s,
    %(region)s,
    %(code_iris)s,
    %(centroid_lat)s,
    %(centroid_lon)s,
    %(date_mise_en_service)s,
    %(station_meteo_id)s,
    %(station_meteo_nom)s,
    %(station_meteo_lat)s,
    %(station_meteo_lon)s,
    %(distance_station_km)s,
    NOW()
)
ON CONFLICT (id_peps) DO UPDATE SET
    nom_installation = EXCLUDED.nom_installation,
    type_energie = EXCLUDED.type_energie,
    code_filiere = EXCLUDED.code_filiere,
    filiere = EXCLUDED.filiere,
    technologie = EXCLUDED.technologie,
    puissance_max_installee = EXCLUDED.puissance_max_installee,
    commune = EXCLUDED.commune,
    departement = EXCLUDED.departement,
    region = EXCLUDED.region,
    code_iris = EXCLUDED.code_iris,
    centroid_lat = EXCLUDED.centroid_lat,
    centroid_lon = EXCLUDED.centroid_lon,
    date_mise_en_service = EXCLUDED.date_mise_en_service,
    station_meteo_id = EXCLUDED.station_meteo_id,
    station_meteo_nom = EXCLUDED.station_meteo_nom,
    station_meteo_lat = EXCLUDED.station_meteo_lat,
    station_meteo_lon = EXCLUDED.station_meteo_lon,
    distance_station_km = EXCLUDED.distance_station_km,
    updated_at = NOW()
WHERE (
    gold.installations_meteo.nom_installation,
    gold.installations_meteo.type_energie,
    gold.installations_meteo.code_filiere,
    gold.installations_meteo.filiere,
    gold.installations_meteo.technologie,
    gold.installations_meteo.puissance_max_installee,
    gold.installations_meteo.commune,
    gold.installations_meteo.departement,
    gold.installations_meteo.region,
    gold.installations_meteo.code_iris,
    gold.installations_meteo.centroid_lat,
    gold.installations_meteo.centroid_lon,
    gold.installations_meteo.date_mise_en_service,
    gold.installations_meteo.station_meteo_id,
    gold.installations_meteo.station_meteo_nom,
    gold.installations_meteo.station_meteo_lat,
    gold.installations_meteo.station_meteo_lon,
    gold.installations_meteo.distance_station_km
) IS DISTINCT FROM (
    EXCLUDED.nom_installation,
    EXCLUDED.type_energie,
    EXCLUDED.code_filiere,
    EXCLUDED.filiere,
    EXCLUDED.technologie,
    EXCLUDED.puissance_max_installee,
    EXCLUDED.commune,
    EXCLUDED.departement,
    EXCLUDED.region,
    EXCLUDED.code_iris,
    EXCLUDED.centroid_lat,
    EXCLUDED.centroid_lon,
    EXCLUDED.date_mise_en_service,
    EXCLUDED.station_meteo_id,
    EXCLUDED.station_meteo_nom,
    EXCLUDED.station_meteo_lat,
    EXCLUDED.station_meteo_lon,
    EXCLUDED.distance_station_km
);
